import Head from 'next/head'
import Link from "next/link";
import { getListPages } from "./api/notion";

export default function Home({ pages }) {

  console.log({ pages })
  return (
    <div>
      <Head>
        <title>Blog with nextjs and Notion API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ul>
          {pages.map((page) => (
            <li key={page.id}>
              <p>{page.id } - {page.properties.Name.title[0].plain_text}</p>
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}


export const databaseId = process.env.NOTION_DATABASE_ID
export const getStaticProps = async () => {
  const database = await getListPages(databaseId);

  return {
    props: {
      pages: database,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every second
    revalidate: 1, // In seconds
  };
};